### ISSUE TITLE
[Feature] Allow ending game without submitting score

### ISSUE THREAD

**Issue by ElPlaso** [kevinanielsen/flags-game#99]
**Is your feature request related to a problem? Please describe.**
Problem: Game makes you submit score / name when game ends with no way to opt out.

**Describe the solution you'd like**
A skip button added to take you back to main page without having to submit score or clicking back in history. Additionally, allow clicking the app bar title to navigate back to home.

**Describe alternatives you've considered**
n/a

**Additional context**
![image](https://github.com/kevinanielsen/flags-game/assets/66361666/1b98e0a2-a547-48c8-9a6f-ac53b0cfe341)

**Comment by kevinanielsen** [comment]
Sounds like a great feature - Would you like to be assigned to this?

**Comment by ElPlaso** [comment]
> Sounds like a great feature - Would you like to be assigned to this?

Sorry been busy, but yes.

**Comment by kevinanielsen** [comment]
No problem - You've been assigned :)
